### ISSUE TITLE
Prototipo de Baja

### ISSUE THREAD

**Issue by JessIM40** [saamcruzzr/DEV002-social-network#20]
## Propuestas de prototipo en papel:

![Captura de pantalla (24)](https://user-images.githubusercontent.com/112719297/213312080-4e3a867c-818e-4214-b58e-a0602039c7a5.png)

![Captura de pantalla (23)](https://user-images.githubusercontent.com/112719297/213312097-65817dbd-bef4-473b-9104-83606ba8ac54.png)

![Captura de pantalla (25)](https://user-images.githubusercontent.com/112719297/213312108-e110f4b7-f75c-4ee2-81c8-0d60040ccba2.png)

## Prototipo de baja en figma:
![Captura de pantalla (26)](https://user-images.githubusercontent.com/112719297/213312648-82373b74-ca7a-4a80-b98d-9ca37697528f.png)

**Comment by FerRomero1990** [comment]
Prototipo desktop

![Image](https://user-images.githubusercontent.com/113949903/214185541-a7894259-5114-417c-ab6f-073580a52d21.jpeg)
